### ISSUE TITLE
DDIA

### ISSUE THREAD

**Issue by yuchenzhong** [yuchenzhong/cs-notes#33]
必须的

**Comment by vycezhong** [comment]
## Ch 1: Reliable, Scalable, and Maintainable Applications 

Data-intensive: 与compute-intensive相反，CPU不是瓶颈，数据是主要挑战. 常见的数据密集型系统如databases, caches, search indexes, stream processing, batch processing. 

数据密集型系统最重要的三个特质: 

- **Reliability**: The system should continue to work correctly (performing the correct function at the desired level of performance) even in the face of adversity (hardware or software faults, and even human error). 
- **Scalability**: As the system grows (in data volume, traffic volume, or complexity), there should be reasonable ways of dealing with that growth. 
- **Maintainability**: Over time, many different people will work on the system (engineering and operations, both maintaining current behavior and adapting the system to new use cases), and they should all be able to work on it productively. 

### Reliability

reliability基本可以理解为: continue to work correctly, even when things go wrong. "things go wrong"叫做faults, 系统能够处理fault称之为fault-tolerance. 

**注意fault和failure不一样. fault指的是系统某个component异常，而failure是指整个系统停止提供用户所需要的服务.** 我们不可能将fault的概率降低到0,但是可以设计一个fault-tolerance的机制来防止fault导致failure. 另外，还有一个词也经常出现 - error. 区分fault和failure对于fault-tolerance系统非常重要. error这个词会导致一定的歧义. 在一些作品中，error一词和fault同义，可以互换. 

摘录下 https://resources.sei.cmu.edu/asset_files/TechnicalReport/1992_005_001_16112.pdf

> Every fault is a failure from some point of view.
> A system with faults may continue to provide its service, that is, not fail. Such a system is saidto befault tolerant.

**Comment by vycezhong** [comment]
## Data Models and Query Languages 

主要分析和比较了relational databases和document databases的利与弊

> The main arguments in favor of the document data model are schema flexibility, better performance due to locality, and that for some applications it is closer to the data structures used by the application. The relational model counters by providing better support for joins, and many-to-one and many-to-many relationships.

关于为何document databases又locality优势:

> A document is usually stored as a single continuous string, encoded as JSON, XML, or a binary variant thereof (such as MongoDB’s BSON). If your application often needs to access the entire document (for example, to render it on a web page), there is a performance advantage to this storage locality. If data is split across multiple tables, like in Figure 2-1, multiple index lookups are required to retrieve it all, which may require more disk seeks and take more time.

very interesting. 实际上这两种数据库正在合流. 现在流行的数据库，如PostgreSQL，MySQL等同样支持JSON documents.

**Comment by vycezhong** [comment]
## Chapter 3: Storage and Retrieval 

存储引擎一般分为两类: log-structured和page-oriented.

log-structured和在OSTEP里面介绍的log-structured filesystem很像啊. idea是一样的，都是写入只做append. 读取是查找最新的record. 但naive的查找就需要linear scan，复杂度是O(N)，N是records数量. 这肯定不可行. 为了降低查找速度，我们需要增加一些indices来方便查找. 

最简单的indices就是hash indices. 比如如果是存储key-value data，那么可以in-memory存储一个key-offset的hashmap，其中key就是key-value的key，offset是这个key-value所在文件的offset. 这样查找的时候，直接in-memory查找文件的offset是哪里，然后从磁盘读取. 这个方法对于写入操作也基本没有什么开销，因为indices都是in-memory的. 如果出现故障，in-memory hash map丢失了，也没有关系，因为可以通过扫描文件来重建indicecs，只不过时间可能会较长，所以可以考虑定期保存in-memory hash map的snapshot. 为了保证文件不会越来越大直到超过磁盘大小，我们需要设定一个segment size，当文件大小超过了segment size后，后续的写入就写到一个新的文件. 同时，系统可以对旧文件进行压缩操作，即将冗余的key合并. hash indices的一个缺点是无法进行range queries. 比如，不能查找范围学号在1234到4321之间的学生信息.

**Comment by vycezhong** [comment]
## Chapter: Encoding and Evolution

如果要将in-memory的数据结构保存成文件，或者通过网络传输，就需要进行数据编码. 大致可以分为这么几种方式:
- 语言自带的序列化库
- JSON, XML这种textual format
- Thrift, Protocal Buffer这种binary编码 

最后一个应该是分布式系统中最常用的. 

数据流有这么几种形式:
- database: 写数据的进程进行编码，读数据的进行进行解码
- RPC, REST API: client编码请求，server解码请求，然后编码响应，client解码响应. 
- Asynchronous message passing（messages brokers or actors）: 节点之间互相通信，发送者编码，接收者解码.

**Comment by vycezhong** [comment]
## Chapter 5: Replication

主要分三种: single-leader, multi-leader和leaderless. 第一种最简单，就是所有写请求都交给leader，leader再forward到followers上，读请求可以从任何一个replica读. 这个又可以分为同步和异步. 同步是指只有当所有followers都完成了写入操作，client的写操作才返回成功，而异步则只需要leader写入完成即可. 一般会让一个follower同步，其他followers都是异步. multi-leader适用于多个datacenter的情况，每个datacenter有一个leader. 但有多个leader会产生conflicts. conflicts一般需要一些预先设定的规则来resolve，比如last write wins (LWW). 最后是leaderless，这个方法我挺喜欢的，也是Amazon dynamo所提出来的方法. 简单来说，当client向数据库做写入操作的时候，它会向w个replicas写入，而当client读取的时候，向r个replicas读取，只要w + r > n，n是replicas数量，那么就一定可以保证至少有一个replica返回的是最新值. 像这样的读写操作，叫做quorum读写. 这个idea很漂亮. 不过还是会有一些edge cases. 最后谈到了concurrent write，这里说的并行，是指逻辑上的，即没有causal dependency的. 关于这方面内容，可以参考我之前关于[lamport clock](https://github.com/vycezhong/cs-notes/issues/1#issuecomment-827691617)的笔记.

**Comment by vycezhong** [comment]
## Chapter 6: Partitioning

根据key来partition. 可以直接根据key来partition，也可以根据hash(key)来partition，但hash(key)的问题是无法直接进行range查询. 对于二级索引，有两种partition方式，一种根据document来分，这是local indices，因为写入操作只需要更新本机上的二级索引就行了，但对于查询而言，要慢一些因为client需要向所有partition发送查询请求;另一种根据term来分，这是global indices，这样查询会快一些因为client只需要向一个partition发送请求，而平时的写入会变慢因为涉及到跨partition的二级索引更新. 最后是谈到了如何rount请求啊，比如进行了一次rebalancing之后，client需要怎么找到一个key到底在哪个partition上？目前的解决办法是routing tier + ZooKeeper. routing tier就是个代理，负责转发请求和响应. ZooKeeper负责跟踪集群的metadata. 每个节点都会在Zookeeper注册，Zookeeper会维护一个partition to nodes的映射. 而其他角色，比如routing tier或者client，可以订阅Zookeeper中的信息. 当有一个partition发生改变的时候，或者有新的节点加入或者移除的时候，Zookeeper会通知subscribers. 很不错. 

![image](https://user-images.githubusercontent.com/25879526/152680356-2f3b0b3a-ff4b-4da0-a3dc-8c16fa94b7ee.png)

**Comment by vycezhong** [comment]
## Chapter 8: The Troubles with Distributed Systems 

明白了distributed system和单机多进程/线程并行是存在本质区别的：分布式系统中，任何一个节点都可能会挂，网络可能会发生故障，可靠的通信是不存在的.

**Comment by vycezhong** [comment]
## Chapter 9: Consistency and Consensus

这一节和 #1 讲的内容差不多其实. 从线性化讲到consensus. 线性化简单来说就是看上去就像只有一个replica. 区别于causal total，线性化是不存在同时发生这个概念的，一般需要Lamport Lock来确定total order. 但线性化一般都很慢. 

后面还提到了2PC. 2PC其实就是一种consensus算法 - 是都写入还是都不写入. 2PC有一个global coordinator，第一步是coordinator问所有participant是否prepare. 如果所有participants回答yes，那么coordinator就决定做commit，并且将这个决定持久化到disk，以便coordinator crash后还能继续执行决定. 发送commit命令到所有participants，participant接收到commit命令后进行commit，然后向coordinator回复ok. 如果在第一阶段只要有一个participant回答no，那么coordinator发送abort命令. 如果在第二阶段，coordinator的commit命令在网络传输中丢失，或者participant的回复在网络传输中丢失，那么coordinator将会无限retry，因为decision is made. 

consensus algorithms，比如RAFT，非常有用. membership service需要它们. 一般用来确定leader啊什么的. 很多问题其实都是consensus问题，比如

![image](https://user-images.githubusercontent.com/25879526/154501506-eed58a41-ff95-48b3-85e8-89a430f684fa.png)

**Comment by yuchenzhong** [comment]
读完了. 忘记关了.
